name: "davidkhala/rootless-docker"
description: "Run Docker in Rootless Mode on Linux"

branding:
  icon: "lock"
  color: "purple"

runs:
  using: "composite"
  steps:
    - name: Stop rootful Docker daemon.
      run: sudo systemctl stop docker.service
      shell: bash
    - name: Configure AppArmor
      shell: bash
      run: |
        abi4_version="$(find /etc/apparmor.d/abi -maxdepth 1 -name '4.*' -printf '%f\n' | sort -nr | head -1)"
        filename=$(echo $HOME/bin/rootlesskit | sed -e s@^/@@ -e s@/@.@g)
        cat <<EOF > ~/${filename}
          abi <abi/${abi4_version}>,
          include <tunables/global>

          "$HOME/bin/rootlesskit" flags=(unconfined) {
            userns,

            include if exists <local/${filename}>
          }
        EOF
        sudo mv ~/${filename} /etc/apparmor.d/${filename}
        sudo systemctl restart apparmor.service
    - name: Install rootless Docker
      shell: bash
      run: curl -fsSL https://get.docker.com/rootless | sh
      env:
        FORCE_ROOTLESS_INSTALL: 1
    - name: Configure
      shell: bash
      run: echo ~/bin >>"$GITHUB_PATH"
        
        